### PR TITLE
Namespace LESS variables

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by jbuck** [comment]
@vazquez r?

**Comment by vazquez** [comment]
:+1:

**Comment by flodolo** [comment]
You may want to check what you're doing with Bugzilla hooks, given that you modified a 3 digits bug last night
https://bugzilla.mozilla.org/show_bug.cgi?id=101

**Comment by jbuck** [comment]
Argh! I keep on getting the syntax mixed up between github issues and bugzilla bugs. Thanks for pointing that out @flodolo

**Pull request merged**
